### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PhanaticD** [Ichbinjoe/MCAuthenticator#21]
```
[21:11:16 WARN]: Could not pass incoming plugin message to MCAuthenticator v2.0.3
java.lang.NullPointerException
        at io.ibj.mcauthenticator.engine.events.PluginMessageEvent.onPluginMessageReceived(PluginMessageEvent.java:28) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:2534) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.2.jar:git-Paper-1009]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1009]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

**Comment by Ichbinjoe** [comment]
Please post logs +- 10 lines

**Comment by Ichbinjoe** [comment]
Caused by race condition between bungee and bukkit servers. Better solution needs implemented - working on fix.
