### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PhanaticD** [Ichbinjoe/MCAuthenticator#22]
```
[00:14:27 INFO]: UUID of player PotatoKing66 is aa46fd46-27fa-4944-ac4d-ed99e0f358dd
[00:14:27 INFO]: Creating empty config: /root/prison/plugins/Essentials/userdata/159018b3-99d3-3f9f-a9c0-759dbd304821.yml
[00:14:27 INFO]: CH: Running original command on player PotatoKing66 ----> /guidebook
[00:14:27 INFO]: [Essentials] Found new UUID for PotatoKing66. Replacing 159018b3-99d3-3f9f-a9c0-759dbd304821 with aa46fd46-27fa-4944-ac4d-ed99e0f358dd
[00:14:27 ERROR]: Could not pass event PlayerDropItemEvent to MCAuthenticator v2.0.3
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1029]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.EntityHuman.a(EntityHuman.java:582) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.EntityHuman.drop(EntityHuman.java:540) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.CommandGive.execute(SourceFile:75) [patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.craftbukkit.v1_11_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:109) [patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.craftbukkit.v1_11_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:38) [patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) [patched_1.11.2.jar:git-Paper-1029]
        at com.laytonsmith.abstraction.bukkit.BukkitMCServer.dispatchCommand(BukkitMCServer.java:129) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.functions.Meta$sudo.exec(Meta.java:236) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.Script.eval(Script.java:375) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.Script.eval(Script.java:344) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1995) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1952) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.Script.run(Script.java:207) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.AliasCore.alias(AliasCore.java:153) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.functions.Meta$call_alias.exec(Meta.java:496) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.Script.eval(Script.java:375) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.Script.eval(Script.java:344) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.Script.seval(Script.java:253) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.functions.BasicLogic$_if.execs(BasicLogic.java:85) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.Script.eval(Script.java:334) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.Script.eval(Script.java:344) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1995) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1952) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.events.AbstractEvent.execute(AbstractEvent.java:109) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.events.BoundEvent.execute(BoundEvent.java:320) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.events.BoundEvent.trigger(BoundEvent.java:278) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.events.EventUtils.FireListeners(EventUtils.java:253) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.core.events.EventUtils.TriggerListener(EventUtils.java:240) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.laytonsmith.abstraction.bukkit.events.drivers.BukkitPlayerListener.onPlayerJoin(BukkitPlayerListener.java:73) [CommandHelper.jar:3.3.2-SNAPSHOT]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor235.execute(Unknown Source) [?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) [patched_1.11.2.jar:git-Paper-1029]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1029]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:352) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:178) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:153) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:916) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1029]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1029]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at io.ibj.mcauthenticator.engine.events.InventoryEvent.auth(InventoryEvent.java:61) ~[?:?]
        at io.ibj.mcauthenticator.engine.events.InventoryEvent.onDrop(InventoryEvent.java:52) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor284.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1029]
        ... 51 more
[00:14:27 INFO]: [PotatoKing66: Given [§aPrison Information§r] * 1 to PotatoKing66]
[00:14:27 INFO]: PotatoKing66[/121.223.162.150:50293] logged in with entity id 7497 at ([prison]-165.5, 163.0, -30.5)
[00:14:27 INFO]: REMOTE AUTH
[00:14:27 INFO]: Creating empty config: /root/prison/plugins/Essentials/userdata/aa46fd46-27fa-4944-ac4d-ed99e0f358dd.yml

```

**Comment by Ichbinjoe** [comment]
Stems from the fact some plugins start interacting with the player firing events before MCAuthenticator is prepared to start handling them - temporary solution is in place on master currently, and a longer term solution should be considered.

Pushed 0314430 to hopefully correctly handle more of these instances.
