### ISSUE TITLE
The plugin stops working after a server reboot/plugin reload

### ISSUE THREAD

**Issue by ShonP40** [Ichbinjoe/MCAuthenticator#39]
**On Minecraft 1.7.10 after i reboot the server (or reload the plugin) the plugin stops working and then to make it work again i have to reset its save folder.**

### **Here is the log after i start the server:**

```
[18:40:51] [Server thread/INFO]: [MCAuthenticator] Enabling MCAuthenticator v2.0.4
[18:40:51] [Server thread/INFO]: [MCAuthenticator] Using RFC6238 (Google Authenticator 2FA) based authentication.
[18:40:52] [Server thread/ERROR]: Error occurred while enabling MCAuthenticator v2.0.4 (Is it up to date?)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:755) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:694) ~[?:?]
	at io.ibj.mcauthenticator.model.datasource.SingleFileUserDataSource.invalidateCache(SingleFileUserDataSource.java:85) ~[?:?]
	at io.ibj.mcauthenticator.model.datasource.SingleFileUserDataSource.<init>(SingleFileUserDataSource.java:34) ~[?:?]
	at io.ibj.mcauthenticator.Config.<init>(Config.java:73) ~[?:?]
	at io.ibj.mcauthenticator.MCAuthenticator.reload(MCAuthenticator.java:103) ~[?:?]
	at io.ibj.mcauthenticator.MCAuthenticator.onEnable(MCAuthenticator.java:53) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339) ~[?:?]
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168) ~[?:?]
	... 18 more
```

### **Here is the log after i run the command /2fa:**

```
ShonP40 issued server command: /2fa
[18:41:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command '2fa' in plugin MCAuthenticator v2.0.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.NullPointerException
        at io.ibj.mcauthenticator.engine.CommandHandler.printHelp(CommandHandler.java:78) ~[?:?]
        at io.ibj.mcauthenticator.engine.CommandHandler.onCommand(CommandHandler.java:44) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        ... 13 more
```

**Comment by joshuasing** [comment]
does this still happen??

**Comment by ShonP40** [comment]
Yes

**Comment by astei** [comment]
It's possible the single-file configuration got corrupted. You may need to wipe it and force your users to re-link, or use the multi-file configuration which should resist data corruption better.

**Comment by ShonP40** [comment]
It doesn't matter any more as I switched to [MineSecure](https://www.spigotmc.org/resources/minesecure.699/).
